name: PM566 website

on: [push, pull_request]

env:
  cntr: uscbiostats/pm566:latest

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${cntr}

      - name: Building website
        run: docker run --rm -i -v ${PWD}:/home/mnt -w /home/mnt ${cntr} Rscript -e 'blogdown::hugo_build()'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

