name: PM566 website

on: [push, pull_request]

env:
  cntr: uscbiostats/pm566:website

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${cntr}

      - name: Submodule
        run: |
                cd website
                git submodule init
                git submodule update

      - name: Building website
        run: |
                cd website
                docker run --rm -i -v ${PWD}:/home/mnt \
                        -w /home/mnt ${cntr} \
                        Rscript --vanilla build.R

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public

